### ISSUE TITLE
Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by ben-rowe** [kirm/sip.js#148]
Running the basic example make-call.js from the example folder throws this error.

sip.js version 0.06

Any ideas?

```
*******/sip.js:1403
          if(hop.host === hostname) {
                 ^

TypeError: Cannot read property 'host' of undefined
    at ************sip.js:1403:18
    at Object.send (/************sip.js:1409:11)
```

Many Thanks
Ben

**Comment by ben-rowe** [comment]
Ignore this user error, URI was incorrect.
